export const gamesData = [
  {
    "title": "Neon Drift",
    "description": "Slide through synthwave grids avoiding firewalls and scanning lasers in this neon arcade runner.",
    "genre": "Arcade / Racing",
    "developer": "Abhirag R Nair & Johan Gejo",
    "engine": "Unity",
    "dimension": "3D",
    "duration": "1h",
    "coverUrl": "",
    "year": "2025",
    "isEditorsChoice": true,
  },
  {
    "title": "Hollow Maze",
    "description": "A dark rogue-lite puzzle explorer where your flashlight is your only defense against creeping glitches.",
    "genre": "Puzzle / Horror",
    "developer": "Aleena Thomas & Nidhim Nair",
    "engine": "Godot",
    "dimension": "2D",
    "duration": "2h",
    "coverUrl": "",
    "year": "2025",
    "isEditorsChoice": false,
  },
  {
    "title": "Grid Runner",
    "description": "Deconstruct obstacles by shooting packets of debug data at compiling compiler errors.",
    "genre": "Shooter / Retro",
    "developer": "Gagandeep M",
    "engine": "Custom",
    "dimension": "2D",
    "duration": "30m",
    "coverUrl": "",
    "year": "2025",
    "isEditorsChoice": false,
  },
  {
    "title": "Coda: The Last Protocol",
    "description": "A visual novel / terminal simulator where your choices compile the fate of an isolated AI server room.",
    "genre": "Simulation / Narrative",
    "developer": "GDSC Game Dev Team",
    "engine": "Web",
    "dimension": "2D",
    "duration": "4h",
    "coverUrl": "",
    "year": "2024",
    "isEditorsChoice": false,
  }
];
