export const questsData = [
  {
    "title": "Cyberpunk Level Design",
    "category": "Workshops",
    "status": "ACTIVE",
    "dateText": "May 14-16",
    "location": "Virtual",
    "image": "",
    "capacity": 50,
    "seatsTaken": 12,
    "targetDate": new Date(Date.now() + 12 * 60 * 60 * 1000),
    "recapUrl": null,
  },
  {
    "title": "Sound Design Masterclass",
    "category": "Workshops",
    "status": "UPCOMING",
    "dateText": "June 02",
    "location": "Main Hall",
    "image": "",
    "capacity": 30,
    "seatsTaken": 0,
    "targetDate": new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    "recapUrl": null,
  },
  {
    "title": "Intro to Game Development",
    "category": "Workshops",
    "status": "UPCOMING",
    "dateText": "June 15",
    "location": "Lab 1",
    "image": "",
    "capacity": 25,
    "seatsTaken": 0,
    "targetDate": new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    "recapUrl": null,
  },
  {
    "title": "Game Jam #3 - April 2025",
    "category": "Game_Jams",
    "status": "COMPLETED",
    "dateText": "April 2025",
    "location": "Virtual",
    "image": "",
    "capacity": 100,
    "seatsTaken": 100,
    "targetDate": new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Sound Design Masterclass",
    "category": "Workshops",
    "status": "UPCOMING",
    "dateText": "June 02",
    "location": "Main Hall",
    "image": "",
    "capacity": 30,
    "seatsTaken": 0,
    "targetDate": new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    "recapUrl": null,
  },
  {
    "title": "Sound Design Masterclass",
    "category": "Workshops",
    "status": "UPCOMING",
    "dateText": "June 02",
    "location": "Main Hall",
    "image": "",
    "capacity": 30,
    "seatsTaken": 0,
    "targetDate": new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    "recapUrl": null,
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  },
  {
    "title": "Unity Workshop - March 2025",
    "category": "Workshops",
    "status": "COMPLETED",
    "dateText": "March 2025",
    "location": "Lab 1",
    "image": "",
    "capacity": 50,
    "seatsTaken": 50,
    "targetDate": new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    "recapUrl": "#",
  }
];
